[package]
name = "source"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
nix = { version = "0.30.1", features = ["socket", "fs", "signal"] }
